import { Bell, Flag, Pencil } from "lucide-react";
import { dateDiff } from "../lib/task-date";
import type { ProjectPlan, Task } from "../types";

export interface MilestoneAlert { plan: ProjectPlan; days: number }

export function NotificationCenter({ open, onToggle, onClose, todayKey, overdueTasks, dueTodayTasks, upcomingMilestones, reviewPending, onOpenTask, onGoProjects, onGoToday }: { open: boolean; onToggle: () => void; onClose: () => void; todayKey: string; overdueTasks: Task[]; dueTodayTasks: Task[]; upcomingMilestones: MilestoneAlert[]; reviewPending: boolean; onOpenTask: (taskId: string) => void; onGoProjects: () => void; onGoToday: () => void }) {
  const alertCount = overdueTasks.length + dueTodayTasks.length + upcomingMilestones.length + (reviewPending ? 1 : 0);
  return <div className="notification-wrap"><button className="icon-button notification" title="提醒" onClick={onToggle}><Bell size={19} />{alertCount > 0 && <i />}</button>{open && <><div className="alert-backdrop" onClick={onClose} /><div className="alert-panel"><header><h3>提醒</h3><span>{alertCount > 0 ? `${alertCount} 条待处理` : "暂无待处理"}</span></header>{alertCount === 0 && <p className="alert-empty">一切都安排妥当，没有需要注意的事项。</p>}{overdueTasks.length > 0 && <div className="alert-section"><p>逾期任务 · {overdueTasks.length}</p>{overdueTasks.slice(0, 5).map((task) => <button className="alert-item" key={task.id} onClick={() => { onOpenTask(task.id); onClose(); }}><span className={`priority-dot ${task.priority}`} /><span className="alert-title">{task.title}</span><em>已延 {dateDiff(task.plannedDate, todayKey)} 天</em></button>)}{overdueTasks.length > 5 && <p className="alert-more">还有 {overdueTasks.length - 5} 项，可在“全部任务”中筛选逾期查看。</p>}</div>}{dueTodayTasks.length > 0 && <div className="alert-section"><p>今日截止 · {dueTodayTasks.length}</p>{dueTodayTasks.slice(0, 5).map((task) => <button className="alert-item" key={task.id} onClick={() => { onOpenTask(task.id); onClose(); }}><span className={`priority-dot ${task.priority}`} /><span className="alert-title">{task.title}</span><em>{task.dueAt}</em></button>)}</div>}{upcomingMilestones.length > 0 && <div className="alert-section"><p>项目目标临近</p>{upcomingMilestones.map(({ plan, days }) => <button className="alert-item milestone" key={plan.id} onClick={() => { onGoProjects(); onClose(); }}><Flag size={13} /><span className="alert-title">{plan.name}</span><em>{days >= 0 ? `还剩 ${days} 天` : `已超期 ${-days} 天`}</em></button>)}</div>}{reviewPending && <div className="alert-section"><p>今日复盘</p><button className="alert-item milestone" onClick={() => { onGoToday(); onClose(); }}><Pencil size={13} /><span className="alert-title">今天还没有写复盘，留下一句也很好。</span></button></div>}</div></>}</div>;
}
